apiVersion: v1
kind: Service
metadata:
  name: trend-app-service     
spec:
  selector:
    app: trend-app             
  ports:
  - protocol: TCP
    port: 80                 
    targetPort: 3000           
  type: LoadBalancer
