apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app-deployment  
spec:
  selector:
    matchLabels:
      app: trend-app          
  template:
    metadata:
      labels:
        app: trend-app      
    spec:
      containers:
      - name: trend-app-container 
        image: parthiban46/trend-app:latest
        ports:
        - containerPort: 3000
